apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: test
  labels:
    service: user-service-test-claim0
  name: user-service-test-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: user-service-pv
status: {}
